apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canarino
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canarino
  template:
    metadata:
      labels:
        app: canarino
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: web
          image: ghcr.io/lerma4/canarino-argocd-demo:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 60s
        - setWeight: 100
